# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f4c9096d7f82f02a4309f7ccb7c5db932579197753b3d9b08c990cdd4d76d5dd8eefed62e937f6a2aaabf313fc2ec237f448449d620a2dd9ec0ce76e1326274

test:
  secret_key_base: f0009fb9c33b6eb447728d4884f995bb4dc0bab5552e7c2f735478eb47a3c77ffd26ad3331a2b6a82519342707e3abc207f0bf9bc453302f172226f5a0a378c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
